name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 sync ./Web/ s3://home.plant.automation.bucket --delete
          --exclude "LICENSE" \
          --exclude "README.md" \
          --exclude "AWS/*" \
          --exclude "ESP-NOW/*" \
          --exclude "SmartHome/*" \
          --exclude "SmartPlant/*" \
          --exclude ".git/*" \
          --exclude ".github/*"

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E17C4EQ4U21Z4C --paths '/*'
